### ISSUE TITLE
Auto-configuration hanging on interval

### ISSUE THREAD

**Issue by locke4** [aanousakis/no-ip#2]
Hi,

I'm trying to run this as a container. I use docker-compose to write my own docker-compose.yml to start the container as a stack. My docker compose is simple and is below. 

When I run, the container comes up correctly, however the console log shows it stopping at the interval configuration. I was expecting to see my environment variable "5" being used but there is no confirmation and I can't see anything else on the log even after leaving it running. I've attached the log file below also. Any assistance or confirmation is greatly appreciated!

docker-compose.yml:
```
version: "2.0"
services:
  noip:
    image: aanousakis/no-ip:latest
    container_name: no-ip
    environment:
      - USERNAME=********.com
      - PASSWORD=********
      - DOMAINS=********.org
      - INTERVAL=5
    restart: unless-stopped
```

console log:
```
Check and import env variables
Checking filename env variables
Secret filenames doesn't exist
Checking if env variables exist
env variables exist
Starting process to generate config file
username ********.com
password ********
domains ********.org
interval 5
spawn noip2 -C
Found 1 adapters
Auto configuration for Linux client of no-ip.com.
Please enter the login/email string for no-ip.com  matched 1
********.com
Please enter the password for user '********.com'  ************
Only one host [******.org] is registered to this account.
It will be used.
Please enter an update interval:[30]  hosts found : 30
```
